"""
Temperature threshold strategy for Polymarket weather markets.

Identifies markets asking "Will temperature in [city] be ≥ [X]°F on [date]?"
and compares the market price against a weather-data-derived probability.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional

import numpy as np

from weather.open_meteo import (
    OpenMeteoClient,
    DailyForecast,
    fahrenheit_to_celsius,
    celsius_to_fahrenheit,
)
from polymarket.markets import ParsedWeatherMarket


@dataclass
class TradeSignal:
    """A trading signal generated by a strategy."""
    condition_id: str
    token_id: str
    outcome: str  # "Yes" or "No"
    side: str     # "BUY" or "SELL"
    market_price: float
    model_probability: float
    edge: float  # model_probability - market_price (positive = BUY Yes)
    size_usdc: float
    market_question: str
    strategy: str
    confidence: float
    explanation: str


class TemperatureStrategy:
    """Strategy for temperature threshold markets.

    Core idea: Get weather forecast for the target date, model
    the temperature distribution, and compare P(temp ≥ threshold)
    against the market's implied probability (price).

    We buy YES when our probability > market price + edge
    We buy NO when our probability < market price - edge
    """

    MIN_EDGE = 0.05         # Minimum 5% edge to trade
    MIN_CONFIDENCE = 0.6    # Minimum parse confidence
    MAX_FORECAST_DAYS = 16  # Open-Meteo max
    DEFAULT_POSITION_USDC = 100

    def __init__(self, open_meteo: OpenMeteoClient):
        self.weather = open_meteo

    async def evaluate(
        self,
        parsed: ParsedWeatherMarket,
        market_price_yes: float,
        token_id_yes: str,
        token_id_no: str = "",
        max_position: float = 100,
    ) -> Optional[TradeSignal]:
        """Evaluate a temperature market for a trading opportunity.

        Args:
            parsed: Parsed market question
            market_price_yes: Current price of YES shares (0-1)
            token_id_yes: CLOB token ID for YES
            token_id_no: CLOB token ID for NO
            max_position: Max USDC to risk on this trade

        Returns:
            TradeSignal if there's an edge, None otherwise.
        """
        if parsed.metric != "temperature":
            return None
        if parsed.confidence < self.MIN_CONFIDENCE:
            return None
        if not parsed.city:
            return None

        # Determine target date
        target_date = parsed.target_date
        if not target_date:
            return None

        # Calculate forecast days
        today = datetime.now().date()
        forecast_days = (target_date - today).days

        if forecast_days < 0:
            return None  # Date already passed
        if forecast_days > self.MAX_FORECAST_DAYS:
            # Too far out for reliable forecast
            # Still evaluate but with lower confidence
            pass

        # Geocode location
        location = await self.weather.geocode_first(parsed.city, parsed.state)
        if not location:
            return None

        # Fetch forecast
        actual_days = min(forecast_days + 2, self.MAX_FORECAST_DAYS)
        forecast = await self.weather.get_forecast(
            latitude=location.latitude,
            longitude=location.longitude,
            forecast_days=actual_days,
            include_ensemble=True,
        )

        # Find the forecast for the target date
        target_forecast = None
        for df in forecast.daily:
            if df.date == target_date:
                target_forecast = df
                break

        if not target_forecast:
            # Use closest day if exact date not available
            if forecast_days < len(forecast.daily):
                target_forecast = forecast.daily[forecast_days]
            elif forecast.daily:
                target_forecast = forecast.daily[-1]
            else:
                return None

        # Calculate our probability
        threshold_c = parsed.temp_threshold_c
        if threshold_c is None:
            # Try to extract from other sources
            if parsed.temp_threshold_f is not None:
                threshold_c = fahrenheit_to_celsius(parsed.temp_threshold_f)
            else:
                return None  # No threshold to evaluate

        # Determine if we're testing "above" or "below"
        above = parsed.temp_direction != "below"

        # Calculate P(temp ≥ threshold) or P(temp ≤ threshold)
        model_prob = self.weather.temperature_probability(
            target_forecast, threshold_c, above
        )

        # Adjust for forecast distance (more uncertainty = probability closer to 0.5)
        if forecast_days > 7:
            # Shrink toward 0.5 as uncertainty grows
            shrinkage = min((forecast_days - 7) / 9.0, 0.4)  # Max 40% shrinkage
            model_prob = model_prob * (1 - shrinkage) + 0.5 * shrinkage

        # Calculate edge
        # For "above" markets: we want to buy YES when model_prob > price
        # For "below" markets: we want to buy YES when model_prob > price
        edge = model_prob - market_price_yes

        abs_edge = abs(edge)
        if abs_edge < self.MIN_EDGE:
            return None

        # Scale position by edge magnitude and confidence
        edge_multiplier = min(abs_edge / self.MIN_EDGE, 3.0)  # Cap at 3x
        size_usdc = round(max_position * min(edge_multiplier * 0.33, 1.0) * parsed.confidence, 2)

        if size_usdc < 1:
            return None  # Too small

        if edge > 0:
            # BUY YES: our probability > market price
            side = "BUY"
            outcome = "Yes"
            token_id = token_id_yes
            explanation = (
                f"Model prob {model_prob:.1%} > market {market_price_yes:.1%} "
                f"(edge: {edge:+.1%}). Forecast: {target_forecast.temp_max:.1f}°C max, "
                f"std={target_forecast.temp_max_std:.1f}°C. "
                f"Threshold: {threshold_c:.1f}°C. "
                f"Direction: {'above' if above else 'below'}. "
                f"Forecast days out: {forecast_days}."
            )
        else:
            # BUY NO: our probability < market price
            side = "BUY"
            outcome = "No"
            token_id = token_id_no
            explanation = (
                f"Model prob {model_prob:.1%} < market {market_price_yes:.1%} "
                f"(edge: {edge:+.1%}). Forecast: {target_forecast.temp_max:.1f}°C max "
                f"(threshold: {threshold_c:.1f}°C). "
                f"Buying NO at implied {1-market_price_yes:.1%}."
            )

        if not token_id:
            return None

        return TradeSignal(
            condition_id=parsed.condition_id,
            token_id=token_id,
            outcome=outcome,
            side=side,
            market_price=market_price_yes if outcome == "Yes" else 1 - market_price_yes,
            model_probability=model_prob,
            edge=abs_edge,
            size_usdc=size_usdc,
            market_question=parsed.raw_question,
            strategy="TemperatureThreshold",
            confidence=parsed.confidence,
            explanation=explanation,
        )
